CHARACTERS = [
	{'name': 'Allison', 'gender': 1},
	{'name': 'Ananda', 'gender': -1},
	{'name': 'Charisma', 'gender': 2},
	{'name': 'Clark', 'gender': -1},
	{'name': 'Clakka', 'gender': 1},
	{'name': 'Ender', 'gender': -1},
	{'name': 'Entropy', 'gender': -1},
	{'name': 'Ffyrnig Aderyn', 'gender': 1},
	{'name': 'Haditha', 'gender': 1},
	{'name': 'Kitten Deathpounce', 'gender': 1},
	{'name': 'Jess Couteau', 'gender': 1},
	{'name': 'Magaid Rhoswyn', 'gender': 1},
	{'name': 'Maggie', 'gender': 1},
	{'name': 'Marelli', 'gender': 1},
	{'name': 'Nog', 'gender': 3},
	{'name': 'Nosferatu', 'gender': -1},
	{'name': 'Schlock', 'gender': 0},
	{'name': 'Surolam', 'gender': 1},
	{'name': 'Tachyon', 'gender': 1},
	{'name': 'Val Deathspeaker', 'gender': 1},
]

GROUPS = [
	{'name': 'Blood Legion'},
	{'name': 'Grey Council'},
	{'name': 'LLC, Incorporated'},
	{'name': 'Professional Bowlers'' Association'},
	{'name': 'Q Continuum'},
	{'name': 'Universal Animation Society'},
]

LOCATIONS = [
	{'name': 'Axanar'},
	{'name': 'Bluebell Park'},
	{'name': 'Dis'},
	{'name': 'Earth'},
	{'name': 'Eros'},
	{'name': 'Makemake'},
	{'name': 'Mars'},
	{'name': 'Mercury'},
	{'name': 'Jupiter'},
	{'name': 'Neptune'},
	{'name': 'Oisri'},
	{'name': 'Philadelphia'},
	{'name': 'Pluto'},
	{'name': 'Saturn'},
	{'name': 'Tam Elbrun'},
	{'name': 'Texas'},
	{'name': 'Battle Room'},
	{'name': 'Moon'},
	{'name': 'Eiffel Tower'},
	{'name': 'Locust Court'},
	{'name': 'Statue of Liberty'},
	{'name': 'Titan'},
	{'name': 'Uranus'},
	{'name': 'Venus'},
]

TITLES = [
	{'name': 'Captain'},
	{'name': 'Feast-master'},
	{'name': 'Head chef'},
	{'name': 'General'},
	{'name': 'Leader'},
	{'name': 'President'},
	{'name': 'Press Secretary'},
	{'name': 'Principal'},
	{'name': 'Prime Minister'},
	{'name': 'Premier'},
	{'name': 'Supreme Leader'},
	{'name': 'Surgeon General'},
	{'name': 'Tribune'},
	{'name': 'Tsar'},
]
