# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.SmallIntegerField(choices=[(-1, 'Male'), (1, 'Female'), (0, 'Neuter'), (3, 'Muftale'), (2, 'Varies / Other')]),
        ),
    ]
