# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20160723_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='influences',
            field=models.ManyToManyField(to='story.Location'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='story.Character'),
        ),
    ]
